### ISSUE TITLE
US-01 A user shall be able to post a picture

### ISSUE THREAD

**Issue by huangs08** [huangs08/snaptalk#1]
Description: A user can post pictures on their profile page to share with other users.
Point: 15
Risk: 
**High**:
We have to be able to post data to the database. We have to be able to fetch data from the database. We have to post the picture in the profile page and home page at the same time. We have to refresh the home page each time the user posts.
Priority: 
**High**:
It has to be completed first since the comment component depends on it. It will take time to implement it.

**Comment by Manraj45** [comment]
Discord Discussion Key Point:
- Fetch data from Firebase
- Post data to Firebase
- Display pictures in home page and profile page
- Post picture with a caption
