### ISSUE TITLE
US-02 A user shall be able to follow another user

### ISSUE THREAD

**Issue by Manraj45** [huangs08/snaptalk#2]
Description: A follow feature must be added so that users can follow other users. 
Points: 5
Risk: 
**Low**:
A follow button must be created and the number of follower for that user must increment. The number of following must increment.
Priority: 
**Low**:
Will take less time than comment and post pictures. Easy to implement.

**Comment by Manraj45** [comment]
Discord discussion key points:
- Display follow button on profile page of user
- User can also unfollow
- Increment number of follower and following
- Related with post and notification component

**Comment by Mnx458** [comment]
Following is functionnal is the project
