### ISSUE TITLE
US-03 A user shall be able to comment on a post

### ISSUE THREAD

**Issue by N0ot-No0t** [huangs08/snaptalk#3]
Description: A user can comment on their own post or on other user's posts.
Point: 10
Risk: 
**Medium**:
The comment must be stored in the database. The comment must appear next or under the post. The comment must be assigned to a user and a post. A comment box must be created
Priority: 
**Medium**:
Will take less time to implement than the post component since some code can be reused (post and fetch from database). Is part of the core features.

**Comment by Manraj45** [comment]
Discord discussion key points:
- Comment should be under post 
- Comment must display timestamp and username
